---
title: "Austin Growth Model"
author: "Adil Belgaumi"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE, results = "hide"}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(tidyverse, sf, raster, knitr, kableExtra, tidycensus, tigris, FNN, caret,
       yardstick, pscl, plotROC, ggrepel, pROC, grid, gridExtra, viridis, igraph,
       tmap,rasterVis)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")
```

```{r Functions}
quintileBreaks <- function(df,variable) {
    as.character(quantile(df[[variable]],
                          c(.01,.2,.4,.6,.8),na.rm=T))
}

#This function can be used to convert a polygon sf to centroids xy coords.
xyC <- function(aPolygonSF) {
  as.data.frame(
    cbind(x=st_coordinates(st_centroid(aPolygonSF))[,1],
          y=st_coordinates(st_centroid(aPolygonSF))[,2]))
} 

#this function convert a raster to a data frame so it can be plotted in ggplot
rast <- function(inRaster) {
  data.frame(
    xyFromCell(inRaster, 1:ncell(inRaster)), 
    value = getValues(inRaster)) }
```


```{r}
acs_variables <- load_variables(2021, "acs5")

tracts_pop <- get_acs(
  geography = "tract", variables = "B01001_001", state = 48,  geometry = TRUE, 
                county=c("Hays", "Travis", "Williamson","Bastrop","Caldwell"), year = 2021) %>% 
  st_transform(crs = 6578)

st_write(tracts_pop,dsn = "Data/tracts_pop.shp")

lc_2011_100 <- raster("Data/Final/lc_texas_2011_100_final.tif")
lc_2021_100 <- raster("Data/Final/lc_texas_2021_100_Final.tif")
```

Creating the Fishnet
```{r}
Austin_fishnet <- 
  st_make_grid(tracts_pop, 4000) %>%
  st_sf()
```


```{r}
lc_austin_11 <- crop(lc_2011_100, extent(tracts_pop))
lc_austin_21 <- crop(lc_2021_100, extent(tracts_pop))
```

```{r Class Matrices}
devM <- 
  matrix(c(
    0,12,0,
    12,24,1,
    24,Inf,0),
  ncol=3, byrow=T)

forestM <- 
  matrix(c(
    0,12,1,
    12,Inf,0),
    ncol=3, byrow=T
  )

farmM <- 
  matrix(c(
    0,80,0,
    80,90,1,
    90,Inf,0),
    ncol=3, byrow=T
  )

wetlandM <- 
  matrix(c(
    0,90,0,
    90,100,1,
    100,Inf,0),
    ncol=3, byrow=T
  )


oUndevM <- 
  matrix(c(
    0,30,0,
    30,35,1,
    35,50,0,
    50,55,1,
    55,70,0,
    70,75,1,
    75,Inf,0),
    ncol=3, byrow=T
  )

waterM <- 
  matrix(c(
    0,90,0,
    90,100,1,
    100,Inf,0),
    ncol=3, byrow=T
  )

ClassMatrices <- list(devM,forestM,farmM,wetlandM,oUndevM,waterM)
ClassNames <- list("dev","forest","farm","wetland","oUndev","water")

```


```{r}
Raster_list2011 <- c()
Raster_names2011 <- c()
for (x in 1:length(ClassMatrices)){ 
  # Reclassify land cover to the desired land cover type
  data <- reclassify(lc_austin_11, ClassMatrices[[x]])
  # Aggregate to get fraction of cell with that land type
  data <- aggregate(data, fact = 40, FUN = mean)
  # Name the data in the raster x_2011
  names(data) <- paste(ClassNames[[x]],2011,sep="_")
  # Adds the raster to the raster list with the name x_2011_4000
  Raster_list2011 <- c(Raster_list2011,
                assign(
                  paste(ClassNames[[x]],2011,4000,sep="_")
                  ,data))
  Raster_names <-  c(Raster_names,
                     paste(ClassNames[[x]],2011,sep="_"))
  }


```


```{r}

lc_au_11_2000 <- aggregate(lc_austin_11, fact = 40, FUN= max)
lc_au_21_2000 <- aggregate(lc_austin_21, fact = 40, FUN= max)

ggplot() +
  geom_raster(data=rast(Raster_list2011[[1]]) %>% na.omit %>% filter(value > 0),
              aes(x,y,fill=value)) +
  labs(title = "Land Cover, 2011") +
  mapTheme +
  theme(legend.direction="vertical")
```

```{r Aggregate Raster to Fishnet Function, warning = FALSE, message = FALSE}
aggregateRaster <- function(inputRasterList, theFishnet) {
  #create an empty fishnet with the same dimensions as the input fishnet
  theseFishnets <- theFishnet %>% dplyr::select()
  #for each raster in the raster list
  for (i in inputRasterList) {
  #create a variable name corresponding to the ith raster
  varName <- names(i)
  #convert raster to points as an sf
    thesePoints <-
      rasterToPoints(i) %>%
      as.data.frame() %>%
      st_as_sf(coords = c("x", "y"), crs = st_crs(theFishnet)) %>%
      filter(.[[1]] > 0)
  #aggregate to the fishnet
    thisFishnet <-
      aggregate(thesePoints, thisFishnet, mean) %>%
      mutate(!!varName := ifelse(is.na(.[[1]]),0,.[[1]]))
 #add to the larger fishnet
    theseFishnets <- cbind(theseFishnets,thisFishnet)
  }
  #output all aggregates as one large fishnet
   return(theseFishnets)
}
```

```{r}
aggregatedRasters <-
  aggregateRaster(Raster_list2011, Austin_fishnet) %>%
  dplyr::select(all_of(Raster_names))

map <- tm_shape(aggregatedRasters) +
  tm_polygons(col = "dev_2011") +
  tm_shape(aggregatedRasters) +
  tm_polygons(col = "forest_2011") +
  tm_shape(aggregatedRasters) +
  tm_polygons(col = "water_2011") +
  tm_shape(aggregatedRasters) +
  tm_polygons(col = "farm_2011") 
  

map %>% 
  tmap_leaflet()
```


```{r Highway Data to Fishnet}
MSAHighways <-
  st_read("Data/TxDOT_Roadways.shp") %>%
  st_transform(st_crs(tracts_pop)) %>%  
  st_zm() %>% 
  st_intersection(tracts_pop)
```


```{r Development Lag Calc}
nn_function <- function(measureFrom,measureTo,k) {
  #convert the sf layers to matrices
  measureFrom_Matrix <-
    as.matrix(measureFrom)
  measureTo_Matrix <-
    as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
    output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>% 
    dplyr::select(-thisPoint) %>%
    pull()
  
  return(output)  
}

fishnet$lagDevelopment <-
    nn_function(xyC(fishnet),
                xyC(filter(aggregatedRasters,developed==1)),
                2)

ggplot() +
  geom_sf(data=houstonMSA) +
  geom_point(data=fishnet, 
             aes(x=xyC(fishnet)[,1], y=xyC(fishnet)[,2], 
                 colour=factor(ntile(lagDevelopment,5))), size=1.5) +
  scale_colour_manual(values = palette5,
                     labels=substr(quintileBreaks(fishnet,"lagDevelopment"),1,7),
                     name="Quintile\nBreaks") +
  labs(title = "Spatial Lag to 2001 Development",
       subtitle = "As fishnet centroids") +
  mapTheme

tm_shape(Austin_fishnet,
         )
```

